### ISSUE TITLE
Does the exported SAM2 encoder and decoder only support inference images？

### ISSUE THREAD

**Issue by Aimol-l** [vietanhdev/samexporter#17]
I plan to conduct video inference, but it seems that having only encoder and decoder is not enough.
Perhaps it includes：Image encoder，Memory attention. Prompt encoder and mask decoder，Memory encoder，Memory bank. 

![屏幕截图_20240802_152457](https://github.com/user-attachments/assets/aee57721-a92a-44a5-afe1-ffaa330a38b1)

I'm a bit confused.😕

**Comment by vietanhdev** [comment]
Hi @Aimol-l ,
There is no inference code at the moment. Please use the official repo from Meta.
Thank you!

**Comment by MELANCHOLY828** [comment]
> 我打算做视频推理，但是好像只有encoder和decoder还不够， 可能还要包括：Imagecoder，Memory Attention，Prompt Encoder和Mask Decoder，Memory Encoder，Memory Bank。
> 
> ![在我们_20240802_152457](https://private-user-images.githubusercontent.com/56304358/354507065-aee57721-a92a-44a5-afe1-ffaa330a38b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODg1MzYsIm5iZiI6MTcyMzc4ODIzNiwicGF0aCI6Ii81NjMwNDM1OC8zNTQ1MDcwNjUtYWVlNTc3MjEtYTkyYS00NGE1LWFmZTEtZmZhYTMzMGEzOGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA2MDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMDFkNGZiYjQ5ZjY2ODM2NDM5M2IzMzUxZjM3NGY3ZDVjZTUwMTYzNGUwMmUwM2RlNjYxNDViYTFkYjI3YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VRMFFjj8lXX36GoR4rlGcLBco7RR1gdBBrFWhhIOXJk)
> 
> 我有点困惑。😕

I also want to use it for video inference. Does the exported SAM2 encoder and decoder support it?

**Comment by Aimol-l** [comment]
> > 我打算做视频推理，但是好像只有encoder和decoder还不够， 可能还要包括：Imagecoder，Memory Attention，Prompt Encoder和Mask Decoder，Memory Encoder，Memory Bank。
> > ![在我们_20240802_152457](https://private-user-images.githubusercontent.com/56304358/354507065-aee57721-a92a-44a5-afe1-ffaa330a38b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODg1MzYsIm5iZiI6MTcyMzc4ODIzNiwicGF0aCI6Ii81NjMwNDM1OC8zNTQ1MDcwNjUtYWVlNTc3MjEtYTkyYS00NGE1LWFmZTEtZmZhYTMzMGEzOGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA2MDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMDFkNGZiYjQ5ZjY2ODM2NDM5M2IzMzUxZjM3NGY3ZDVjZTUwMTYzNGUwMmUwM2RlNjYxNDViYTFkYjI3YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VRMFFjj8lXX36GoR4rlGcLBco7RR1gdBBrFWhhIOXJk)
> > 我有点困惑。😕
> 
> I also want to use it for video inference. Does the exported SAM2 encoder and decoder support it?

I am try to export Memory_attention module,but failed. this is my code ：https://github.com/Aimol-l/SAM2Export.git
so,I'm stuck。
this is my note graph.
![屏幕截图_20240816_141328](https://github.com/user-attachments/assets/d16dafa9-5196-4ea5-b424-ae41743fcd92)

**Comment by MELANCHOLY828** [comment]
> > > 我打算做视频推理，但是好像只有encoder和decoder还不够， 可能还要包括：Imagecoder，Memory Attention，Prompt Encoder和Mask Decoder，Memory Encoder，Memory Bank。
> > > ![在我们_20240802_152457](https://private-user-images.githubusercontent.com/56304358/354507065-aee57721-a92a-44a5-afe1-ffaa330a38b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3ODg1MzYsIm5iZiI6MTcyMzc4ODIzNiwicGF0aCI6Ii81NjMwNDM1OC8zNTQ1MDcwNjUtYWVlNTc3MjEtYTkyYS00NGE1LWFmZTEtZmZhYTMzMGEzOGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA2MDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMDFkNGZiYjQ5ZjY2ODM2NDM5M2IzMzUxZjM3NGY3ZDVjZTUwMTYzNGUwMmUwM2RlNjYxNDViYTFkYjI3YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VRMFFjj8lXX36GoR4rlGcLBco7RR1gdBBrFWhhIOXJk)
> > > 我有点困惑。😕
> > 
> > 
> > I also want to use it for video inference. Does the exported SAM2 encoder and decoder support it?
> 
> I am try to export Memory_attention module,but failed. this is my code ：https://github.com/Aimol-l/SAM2Export.git so,I'm stuck。 this is my note graph. ![屏幕截图_20240816_141328](https://private-user-images.githubusercontent.com/56304358/358487478-d16dafa9-5196-4ea5-b424-ae41743fcd92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDYyMzksIm5iZiI6MTcyMzgwNTkzOSwicGF0aCI6Ii81NjMwNDM1OC8zNTg0ODc0NzgtZDE2ZGFmYTktNTE5Ni00ZWE1LWI0MjQtYWU0MTc0M2ZjZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEwNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZTk2YTkzNjA2ZGNiOWIwMDJkZDA1NDgzMjU3ZjMzODIxNjNmMWE5NGQ1MzZjMzZlYTRkZDk5NGZjMDEyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LDPN_17bSu_SxR98aZ__kaJxFDWa5DBLLyOwlEFO33c)

你好，请问图片预测的运行成功了吗，我报错
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "e:\anaconda\envs\sam2\lib\site-packages\imread_from_url\imread_from_url.py", line 52, in imread_from_url
    image = cv2.cvtColor(np.array(image, dtype=np.uint8), cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'
不知道是不是版本问题

**Comment by vietanhdev** [comment]
Closing this as answered and documented in v0.5.0: these split SAM2 encoder/decoder graphs support image prediction only. Video inference requires the temporal memory attention, memory encoder, and memory bank from the official tracker, which are intentionally outside the current export contract.
